### ISSUE TITLE
Variety of `bench` values breaking amenity `not null` in `osm_type`

### ISSUE THREAD

**Issue by rustprooflabs** [rustprooflabs/pgosm-flex#119]
# Details

Caused by #110.

Two records discovered, one `bench=unknown` the other `bench=picnic_table`... 

* https://www.openstreetmap.org/node/2045163490
* https://www.openstreetmap.org/node/2360745046#map=8/38.574/-77.047

Should be able to resolve by changing this

```lua
    if object.tags.bench == 'no' then
        return
    end
```

to

```lua
    if object.tags.bench ~= 'yes' then
        return
    end
```

The only [valid values described](https://wiki.openstreetmap.org/wiki/Key:bench) are `yes`/`no` so discarding other values is fine.

**Comment by jacopofar** [comment]
Amazing, I came here to report this bug but I see you already found it :)

I detected it on these nodes:

* Rostock, Germany  https://www.openstreetmap.org/node/2639704177
* Lombardia, Italy https://www.openstreetmap.org/node/663648878

**Comment by rustprooflabs** [comment]
I didn't log it very long before you ended up here!  I particularly like `bench=no;yes` in two of those examples. :1st_place_medal:

This should be fixed soon!

**Comment by rustprooflabs** [comment]
@jacopofar This should be fixed in `main` now, the new `:latest` Docker image will be available shortly!
