### ISSUE TITLE
Fix output file permissions

### ISSUE THREAD

**Issue by rustprooflabs** [rustprooflabs/pgosm-flex#151]
Files saved by Docker process have unfortunate file permissions as root. This is default for Docker and the way the base Postgres image is setup.  

On the Postgres front, see "Arbitrary --user notes"  from https://hub.docker.com/_/postgres/

It seems three workaround options are available, the methods on the above link largely seem to line up with general docker volume file permission resources (non-postgres).  Each workaround involves additional friction for end users of the docker image to handle these changes.

**Comment by rustprooflabs** [comment]
A few resources with reading materials...

https://www.berthon.eu/2018/containers-volumes-and-file-permissions/

https://jtreminio.com/blog/running-docker-containers-as-current-host-user/

https://www.jujens.eu/posts/en/2017/Jul/02/docker-userns-remap/

**Comment by jacopofar** [comment]
I think I got something working with the latest commit in #150 , now the folder is mounted using the current user and the script runs with the same permissions, so the folder can be accessed and deleted directly without that trick of deleting the files from the container.

I have doubts about how to start postgres, the python script uses `pg_isready` and when running as the non-root user one needs to pass the `-U root` flag to find it. I don't know whether there are cases in which this is not the desired behavior, if that's the case there's no need to change the config of postgres initdb in the pgosm image.

**Comment by rustprooflabs** [comment]
It seems this has been worked through for our current needs.  Future issues RE file permissions can be opened as new issues.  Closing.
