### ISSUE TITLE
Makefile - Running docker with UID/GID breaks Sqitch deployment

### ISSUE THREAD

**Issue by rustprooflabs** [rustprooflabs/pgosm-flex#153]
Discovered via #147.  Only affects development process using `make`, and only development related to the deployment of Sqitch and associated data.  It's worth working on a fix but not an immediate priority.  The schema deployed will become more complex and justifies using Sqitch in the future, also makes it easier to keep the Docker/non-Docker process uniform.

## Problem

Running `make` fails on the Sqitch deployment step.  Error is handled to avoid failure (see 666b9cff2e5a6588629e2a99da63590988b92f0c), results in missing `pgosm.roads` data in final output.  Currently see errors such as this in the log output.

```bash
2021-08-15 10:10:33,641:ERROR:pgosm-flex:db:Loading Sqitch schema failed. pgosm schema will not be included in output.
2021-08-15 10:10:33,641:ERROR:pgosm-flex:db:Cannot find your name; run sqitch config --user user.name "YOUR NAME"
```

I attempted quick fixes but my first attempted workaround just changed the error to a different problem.  I didn't want to go down that rabbit hole today, hence this bug.

**Comment by jacopofar** [comment]
I'm on vacation, but I had a similar issue with the pg_isready step in the script and had to specify the user root or by default it uses the current user name to connect to the database

**Comment by rustprooflabs** [comment]
Enjoy your vacation!

**Comment by rustprooflabs** [comment]
Cannot use the same `-U root` option used with `pg_isready`, sqitch command resulted in unknown option error.

```
2021-08-15 14:01:30,199:ERROR:pgosm-flex:db:Unknown option: U
Usage:
      sqitch deploy [options] [<database>]

...
```

The sqitch way to fix this was to add `/etc/sqitch/sqitch.conf` to set regardless of user.
