### ISSUE TITLE
Restructure, cleanup and tests

### ISSUE THREAD

**Issue by rustprooflabs** [rustprooflabs/pgosm-flex#193]
# Details

Recent work (especially #186) has made it clear the code in `docker/pgosm_flex.py` is poorly structured and confusing.  @jacopofar comments in https://github.com/rustprooflabs/pgosm-flex/pull/186#issuecomment-954674770 provides a good starting point to how to approach the structural cleanup.

Also related to #187.  That work will likely cascade into improvements in the [osmp2gsql-tuner project](https://github.com/rustprooflabs/osm2pgsql-tuner) to enable simplified code in this project.

## What to focus on

* Split into multiple modules
* Do function names make sense?
* More pythonic code and/or new python features?
* Unused variables
* Python tests - a few random tests currently, only 23% coverage
* Probably more!

## Help wanted

I am hoping for a series of smaller changes to whittle away at this progressively. I'll be working on this as time permits, if anyone else wants to help please comment here with what parts you plan to work on to avoid duplicate/conflicting efforts.  Submit a PR to the the `dev` branch and mention this issue.  Feel free to ask questions or make suggestions! :smile:

**Comment by jacopofar** [comment]
Nice! I hope to have some time to help

**Comment by rustprooflabs** [comment]
Closing this issue, I think its purpose for tracking has been served.  Additional issues can be opened targeting new, more specific cleanup needed.
