### ISSUE TITLE
If subregion is None script throw on save downloaded pbf

### ISSUE THREAD

**Issue by RobDesideri** [rustprooflabs/pgosm-flex#198]
## What version of PgOSM Flex are you using?

0.4.0 on Docker.

## Docker image

latest

## What did you do exactly?

Executes without subregion.

## What did happen instead?

Error on `pgosm_flex.py`, line [448](https://github.com/rustprooflabs/pgosm-flex/blob/f5fca8e7b87c2a385cfed44a672937c88127e41c/docker/pgosm_flex.py#L448): "No such file or directory".

## What did you do to try analyzing the problem?

In case subregion is `None`, the `filename` is created using `filename = base_name.format(region)` ([ref](https://github.com/rustprooflabs/pgosm-flex/blob/f5fca8e7b87c2a385cfed44a672937c88127e41c/docker/pgosm_flex.py#L263)).  
Now, region is `north-america/us`.  
So `pbf_filename`  will be "**north-america**/us-latest.osm.pbf", so it is stored in a 'north-america' subfolder contained in output dir. But this subfolder not exists, so wget throw "No such file or directory".

**Comment by rustprooflabs** [comment]
@RobDesideri Attempting this same approach should now throw a `ValueError` with guidance about splitting the region into region + subregion.   The `docs/DOCKER-RUN.md` file now has a [Regions and Subregions](https://github.com/rustprooflabs/pgosm-flex/blob/main/docs/DOCKER-RUN.md#regions-and-subregions) section that helps explain this as well.  There may be use cases where the Geofabrik naming/patterns don't work. This set of changes also adds a new `--input-file` option (#192) to override that portion of functionality.

I suspect there are other improvements RE the docs that could be made to better explain all of this.  I am open to any and all suggestions when it comes to make it easier and more understandable!  Let me know if you have other questions or if the work here doesn't fully address the problem.

Thanks!

**Comment by RobDesideri** [comment]
@rustprooflabs great work, thanks!
