### ISSUE TITLE
Version conflict between Lua and Luarocks

### ISSUE THREAD

**Issue by joshbrooks** [rustprooflabs/pgosm-flex#218]
The documentation for "on server" build didn't work in my case. The workaround is to build `luarocks` from source.

## What version of PgOSM Flex are you using?

Master

On server

## What operating system, osm2pgsql, and PostgreSQL/PostGIS versions are you using?

Linux Mint 20.2 64-bit; osm2pgsql built from master; Postgis 14:3.2 docker image

## What did you do exactly?

Following the instructions for the on server build resulted in Lua version 5.3 being the default version and Luarocks version 5.2 being installed, resulting in this error:

```sh
2022-01-20 09:34:23  ERROR: Error loading lua config: ./style/pgosm-meta.lua:3: module 'luasql.postgres' not found:
	no field package.preload['luasql.postgres']
``` 

## What did happen instead?

In order to get around the issue I followed the luarocks website instructions

```
$ wget https://luarocks.org/releases/luarocks-3.8.0.tar.gz
$ tar zxpf luarocks-3.8.0.tar.gz
$ cd luarocks-3.8.0
$ ./configure && make && sudo make install
```

## What did you do to try analyzing the problem?

Checked the versions of Lua and Luarocks then stackoverflowed ;)

**Comment by rustprooflabs** [comment]
Hi!  Thank you for reporting this!

My first thought to address this is to add to the instructions with those steps to manually install luarocks. I imagine it as an "If you have this problem" type of suggestion.

What do you think about that? I'm open to other ideas, PRs are always welcome too :)

**Comment by rustprooflabs** [comment]
@joshbrooks The docs for manual steps now include a troubleshooting section with a [section for this luarocks issue](https://github.com/rustprooflabs/pgosm-flex/blob/main/docs/MANUAL-STEPS-RUN.md#luarocks-not-installed-properly). A reference to the error message and the steps to manually install luarocks.  Hopefully this makes troubleshooting easier for others that may experience this error.
