### ISSUE TITLE
Change default operation to NOT use `pg_dump`

### ISSUE THREAD

**Issue by rustprooflabs** [rustprooflabs/pgosm-flex#266]
# Details

### :warning:  Breaking Change Proposed :warning: 

I expect the Experimental designation will be removed from <del>`--append`</del> `--replication` mode in the near(ish) future, either late 2022 or early 2023.  I am considering making <del>`--append`</del> `--replication` the default recommendation.  With that change, it would be nice to not have to always include `--skip-dump` if that's the recommended / most common method used.  Being Pre 1.0, if this change is going to be made now is the time to do it.

Currently the default is to run `pg_dump` by default, and specify when you don't want it.  Running `pg_dump` doesn't make much sense when using <del>`--append`</del> `--replication`.  The purpose of the `.sql` is to load to your databases.  With append this shouldn't be necessary for the majority of use cases.

The process to export the `.sql` file would use a new option `--pg-dump`.

## Feedback welcome

If you have thoughts on this in either direction let me know. I'm not dedicated to making this change if it will cause a lot of friction with existing users.  My main motivation for this is that I think users will appreciate being able to use <del>`--append`</del> `--replication` and that will gain traction.

**Comment by rustprooflabs** [comment]
Asking for feedback.
https://mastodon.social/@rustprooflabs/109357178475099314
https://twitter.com/RustProofLabs/status/1593094106158628869

**Comment by jacopofar** [comment]
totally makes sense to me, besides it can always be executed with `docker exec` when needed

**Comment by rustprooflabs** [comment]
This change has been made, currently in the `dev` branch and `:dev` Docker image.
