### ISSUE TITLE
Special characters / Control characters not supported in passwords

### ISSUE THREAD

**Issue by jmealo** [rustprooflabs/pgosm-flex#383]
## What version of PgOSM Flex are you using?

0.61 / Latest

## Docker image

N/A

## What did you do exactly?

Try to use a password with `#` `@` and `!` etc.

## What did you expect to happen?

For pgosm-flex to work.

## What did happen instead?
An invalid connection string is generated and various errors are output that indicate an issue with DNS.

## What did you do to try analyzing the problem?
Scream real loud.

**Comment by rustprooflabs** [comment]
@jmealo This should be fixed in the `:latest` image. I'll leave this open for now if you can confirm it fixes your issue that'd be great!

**Comment by rustprooflabs** [comment]
I believe this is fixed in [1.0.1](https://github.com/rustprooflabs/pgosm-flex/releases/tag/1.0.1).  Please re-open if you find that is not the case!  Thanks for reporting!
