### ISSUE TITLE
Improve helpers.get_name() - International support

### ISSUE THREAD

**Issue by rustprooflabs** [rustprooflabs/pgosm-flex#93]
Identified as an area of improvement during 3/31 webinar via question.  Examples:

* `name:en`
* `name:de`

## References

See:

* https://wiki.openstreetmap.org/wiki/Names
* https://wiki.openstreetmap.org/wiki/Multilingual_names

## Assumption

This improvement will involve an env var to set preferred language.  e.g. user can define `PGOSM_LANGUAGE=de` to grab the name in German if it exists.  Would still fall back to existing logic if specific language does not exist.

**Comment by rustprooflabs** [comment]
I had mentioned that "Nothing was done to handle these" RE the `name:<language>` style tags... not entirely true!

From the current (v0.1.2) `helpers.lua`:

```lua
    for k, v in pairs(tags) do
        if starts_with(k, "name:")
            or ends_with(k, ":NAME")
                then
            return v
        end
    end
```

**Comment by frizatch** [comment]
Great! I was thinking it would be useful for someone pulling data to:

- Make sure they get at least one value for a name key
- Then, as a 2nd option, try to select as many as possible in their language of choice if it exists to be able to work with the data more easily

**Comment by rustprooflabs** [comment]
Helpful tidbit to document (from multilingual page).

The assumed env var (e.g. `PGOSM_LANGUAGE=<code>`) uses the code:


"... where code is a lowercase language's ISO 639-1 alpha2 code, or a lowercase ISO 639-2 code if an ISO 639-1 code doesn't exist."

**Comment by rustprooflabs** [comment]
@frizatch I made some progress on this, if you have some time to check it out I'd love any feedback you have! I have verified a couple simple examples with the DC sub-region, I plan to do testing on a larger scale soon.

I pushed a Docker image to [docker hub](https://hub.docker.com/r/rustprooflabs/pgosm-flex) with the changes, tagged with `lang-dev`.  This command runs the container from this image to test the `PGOSM_LANGUAGE` option. 

```bash
docker run --name pgosm -d \
    -v ~/pgosm-data:/app/output \
    -v /etc/localtime:/etc/localtime:ro \
    -e POSTGRES_PASSWORD=mysecretpassword \
    -p 5433:5432 -d rustprooflabs/pgosm-flex:lang-dev
```

Run processing for D.C. using the language code `kn` (Kannada).  Omitting `-e PGOSM_LANGUAGE=kn \` uses the default logic `get_name()` logic.

```bash
docker exec -it \
    -e POSTGRES_PASSWORD=mysecretpassword -e POSTGRES_USER=postgres \
    -e PGOSM_LANGUAGE=kn \
    pgosm bash docker/run_pgosm_flex.sh \
    north-america/us \
    district-of-columbia \
    500 \
    run-all
```


The following query shows the selected name for a place with a tag for the specified language and a place without.

```sql
SELECT osm_id, osm_type, name
    FROM osm.place_polygon 
    WHERE osm_id IN (-5396194, -4603194)
;
```


```bash
osm_id  |osm_type|name         |
--------|--------|-------------|
-4603194|suburb  |Shepherd Park|
-5396194|boundary|ವಾಷಿಂಗ್‌ಟನ್  |
```

**Comment by rustprooflabs** [comment]
I played around with the U.S. West and Laos regions and think this change looks good. I double checked counts of names set in the places and roads layers to ensure I didn't drop out a whole bunch of names on accident.  No issues found there.

Loading with the default functionality generally results in names using the local language for that region.  An example of place names in U.S. West region.

![image](https://user-images.githubusercontent.com/3085224/114467857-c280d980-9ba7-11eb-987b-609f91fef21e.png)

Using `-e PGOSM_LANGUAGE=kn` for U.S. West results in most labels picking up the Kannada option.

![image](https://user-images.githubusercontent.com/3085224/114467942-ecd29700-9ba7-11eb-980a-10a127fd3c97.png)


Using Laos as another example, the default:

![image](https://user-images.githubusercontent.com/3085224/114468138-3de28b00-9ba8-11eb-8802-a0e08cee7b49.png)


Override language to English with `-e PGOSM_LANGUAGE=en` results in most labels using the English option.

![image](https://user-images.githubusercontent.com/3085224/114468215-5d79b380-9ba8-11eb-9459-87cbc9da8a16.png)
